# Generated by Django 5.1.5 on 2025-03-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0041_proctoringsession_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proctoringsession',
            name='completed',
        ),
    ]
