# Generated by Django 5.1.5 on 2025-03-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0043_alter_universityincharge_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyincharge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='universityincharge',
            name='user',
        ),
    ]
