# Generated by Django 5.1.5 on 2025-03-25 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_onlinestatus_user'),
        ('login', '0044_remove_companyincharge_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
    ]
