# Generated by Django 5.1.5 on 2025-03-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_onlinestatus_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinestatus',
            name='user',
        ),
    ]
