# Generated by Django 5.1.5 on 2025-03-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_onlinestatus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinestatus',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254, unique=True),
        ),
    ]
